version: '3'
services:
  db:
    image: postgres:11.4-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=testdb
  app:
    build: ./
    ports:
      - "8080:8080"
#    environment:
#      POSTGRES_HOST: db